/*
 * Generated by gdbus-codegen 2.40.2. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifndef __EXAMPLE_H__
#define __EXAMPLE_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for blog.letrungthang.Example.Interface */

#define THANGLE_TYPE_EXAMPLE_INTERFACE (thangle_example_interface_get_type ())
#define THANGLE_EXAMPLE_INTERFACE(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), THANGLE_TYPE_EXAMPLE_INTERFACE, ThangleExampleInterface))
#define THANGLE_IS_EXAMPLE_INTERFACE(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), THANGLE_TYPE_EXAMPLE_INTERFACE))
#define THANGLE_EXAMPLE_INTERFACE_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), THANGLE_TYPE_EXAMPLE_INTERFACE, ThangleExampleInterfaceIface))

struct _ThangleExampleInterface;
typedef struct _ThangleExampleInterface ThangleExampleInterface;
typedef struct _ThangleExampleInterfaceIface ThangleExampleInterfaceIface;

struct _ThangleExampleInterfaceIface
{
  GTypeInterface parent_iface;


  gboolean (*handle_my_method1) (
    ThangleExampleInterface *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_InArg);

  gboolean (*handle_my_method2) (
    ThangleExampleInterface *object,
    GDBusMethodInvocation *invocation,
    GVariant *arg_InArg);

  void (*my_signal1) (
    ThangleExampleInterface *object,
    const gchar *arg_Value);

  void (*my_signal2) (
    ThangleExampleInterface *object,
    GVariant *arg_Value);

};

GType thangle_example_interface_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *thangle_example_interface_interface_info (void);
guint thangle_example_interface_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void thangle_example_interface_complete_my_method1 (
    ThangleExampleInterface *object,
    GDBusMethodInvocation *invocation,
    const gchar *OutArg);

void thangle_example_interface_complete_my_method2 (
    ThangleExampleInterface *object,
    GDBusMethodInvocation *invocation,
    GVariant *OutArg);



/* D-Bus signal emissions functions: */
void thangle_example_interface_emit_my_signal1 (
    ThangleExampleInterface *object,
    const gchar *arg_Value);

void thangle_example_interface_emit_my_signal2 (
    ThangleExampleInterface *object,
    GVariant *arg_Value);



/* D-Bus method calls: */
void thangle_example_interface_call_my_method1 (
    ThangleExampleInterface *proxy,
    const gchar *arg_InArg,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean thangle_example_interface_call_my_method1_finish (
    ThangleExampleInterface *proxy,
    gchar **out_OutArg,
    GAsyncResult *res,
    GError **error);

gboolean thangle_example_interface_call_my_method1_sync (
    ThangleExampleInterface *proxy,
    const gchar *arg_InArg,
    gchar **out_OutArg,
    GCancellable *cancellable,
    GError **error);

void thangle_example_interface_call_my_method2 (
    ThangleExampleInterface *proxy,
    GVariant *arg_InArg,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean thangle_example_interface_call_my_method2_finish (
    ThangleExampleInterface *proxy,
    GVariant **out_OutArg,
    GAsyncResult *res,
    GError **error);

gboolean thangle_example_interface_call_my_method2_sync (
    ThangleExampleInterface *proxy,
    GVariant *arg_InArg,
    GVariant **out_OutArg,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define THANGLE_TYPE_EXAMPLE_INTERFACE_PROXY (thangle_example_interface_proxy_get_type ())
#define THANGLE_EXAMPLE_INTERFACE_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), THANGLE_TYPE_EXAMPLE_INTERFACE_PROXY, ThangleExampleInterfaceProxy))
#define THANGLE_EXAMPLE_INTERFACE_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), THANGLE_TYPE_EXAMPLE_INTERFACE_PROXY, ThangleExampleInterfaceProxyClass))
#define THANGLE_EXAMPLE_INTERFACE_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), THANGLE_TYPE_EXAMPLE_INTERFACE_PROXY, ThangleExampleInterfaceProxyClass))
#define THANGLE_IS_EXAMPLE_INTERFACE_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), THANGLE_TYPE_EXAMPLE_INTERFACE_PROXY))
#define THANGLE_IS_EXAMPLE_INTERFACE_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), THANGLE_TYPE_EXAMPLE_INTERFACE_PROXY))

typedef struct _ThangleExampleInterfaceProxy ThangleExampleInterfaceProxy;
typedef struct _ThangleExampleInterfaceProxyClass ThangleExampleInterfaceProxyClass;
typedef struct _ThangleExampleInterfaceProxyPrivate ThangleExampleInterfaceProxyPrivate;

struct _ThangleExampleInterfaceProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  ThangleExampleInterfaceProxyPrivate *priv;
};

struct _ThangleExampleInterfaceProxyClass
{
  GDBusProxyClass parent_class;
};

GType thangle_example_interface_proxy_get_type (void) G_GNUC_CONST;

void thangle_example_interface_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
ThangleExampleInterface *thangle_example_interface_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
ThangleExampleInterface *thangle_example_interface_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void thangle_example_interface_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
ThangleExampleInterface *thangle_example_interface_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
ThangleExampleInterface *thangle_example_interface_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define THANGLE_TYPE_EXAMPLE_INTERFACE_SKELETON (thangle_example_interface_skeleton_get_type ())
#define THANGLE_EXAMPLE_INTERFACE_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), THANGLE_TYPE_EXAMPLE_INTERFACE_SKELETON, ThangleExampleInterfaceSkeleton))
#define THANGLE_EXAMPLE_INTERFACE_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), THANGLE_TYPE_EXAMPLE_INTERFACE_SKELETON, ThangleExampleInterfaceSkeletonClass))
#define THANGLE_EXAMPLE_INTERFACE_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), THANGLE_TYPE_EXAMPLE_INTERFACE_SKELETON, ThangleExampleInterfaceSkeletonClass))
#define THANGLE_IS_EXAMPLE_INTERFACE_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), THANGLE_TYPE_EXAMPLE_INTERFACE_SKELETON))
#define THANGLE_IS_EXAMPLE_INTERFACE_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), THANGLE_TYPE_EXAMPLE_INTERFACE_SKELETON))

typedef struct _ThangleExampleInterfaceSkeleton ThangleExampleInterfaceSkeleton;
typedef struct _ThangleExampleInterfaceSkeletonClass ThangleExampleInterfaceSkeletonClass;
typedef struct _ThangleExampleInterfaceSkeletonPrivate ThangleExampleInterfaceSkeletonPrivate;

struct _ThangleExampleInterfaceSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  ThangleExampleInterfaceSkeletonPrivate *priv;
};

struct _ThangleExampleInterfaceSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType thangle_example_interface_skeleton_get_type (void) G_GNUC_CONST;

ThangleExampleInterface *thangle_example_interface_skeleton_new (void);


G_END_DECLS

#endif /* __EXAMPLE_H__ */
